# Generated by Django 4.1.2 on 2022-10-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='bolas',
            field=models.FloatField(default=0, verbose_name='Quantas bolas de tenis cabem em uma limosine?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='casado',
            field=models.FloatField(default=0, verbose_name='Quantas vezes já foi casado?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='certificacoes_gestao',
            field=models.FloatField(default=0, verbose_name='Quantos certificações tem na área de gestão?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='certificacoes_seguranca',
            field=models.FloatField(default=0, verbose_name='Quantos certificações tem na área de segurança do trabalho?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='certificacoes_tecnologia',
            field=models.FloatField(default=0, verbose_name='Quantos certificações tem na área de tecnologia?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='demissoes',
            field=models.FloatField(default=0, verbose_name='Quantas vezes já foi mandado embora?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='discriminado',
            field=models.FloatField(default=0, verbose_name='Quantas vezes já se sentiu discriminado?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='empregos',
            field=models.FloatField(default=0, verbose_name='Quantos empregos já teve?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='filhos',
            field=models.FloatField(default=0, verbose_name='Quantos filhos você tem?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='graduacoes',
            field=models.FloatField(default=0, verbose_name='Quantas graduações você tem?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='horas_gestao',
            field=models.FloatField(default=0, verbose_name='Quantas horas de cursos tem na área de gestão?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='horas_segurança',
            field=models.FloatField(default=0, verbose_name='Quantas horas de cursos tem na área de segurança do trabalho?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='horas_tecnologia',
            field=models.FloatField(default=0, verbose_name='Quantas horas de cursos tem na área de tecnologia?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='papeis',
            field=models.FloatField(default=0, verbose_name='Quantos papéis já publicou na área de tecnologia da informação?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='receber',
            field=models.FloatField(default=0, verbose_name='Quanto você ou quer receber?'),
            preserve_default=False,
        ),
    ]
