# Generated by Django 4.1.2 on 2022-10-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0002_remove_person_bio_remove_person_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='previsao',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
