# Generated by Django 4.1.2 on 2022-10-18 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economia', '0003_person_previsao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='previsao',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
